// Datos de ejemplo para TallerCRM
window.SEED_DATA = {
  productos: [
    { id: 'p1', nombre: 'Filtro de aceite', descripcion: 'Filtro aceite universal compatible mayoría vehículos', sku: 'FLT-001', stock: 24, stockMinimo: 5, precioCompra: 3.50, precioVenta: 8.90, proveedor: 'AutoParts SL' },
    { id: 'p2', nombre: 'Pastillas de freno delanteras', descripcion: 'Juego pastillas freno delanteras cerámicas', sku: 'FRN-002', stock: 8, stockMinimo: 3, precioCompra: 18.00, precioVenta: 42.00, proveedor: 'FrenoBrake Pro' },
    { id: 'p3', nombre: 'Aceite motor 5W40 (5L)', descripcion: 'Aceite sintético 5W40, lubricante motor gasolina/diesel', sku: 'ACE-003', stock: 30, stockMinimo: 10, precioCompra: 22.00, precioVenta: 38.00, proveedor: 'LubriMax SA' },
    { id: 'p4', nombre: 'Bujías (juego 4)', descripcion: 'Bujías de iridio para motores 4 cilindros', sku: 'BUJ-004', stock: 2, stockMinimo: 4, precioCompra: 12.00, precioVenta: 28.00, proveedor: 'AutoParts SL' },
    { id: 'p5', nombre: 'Correa distribución', descripcion: 'Correa distribución reforzada, compatible SEAT/VW', sku: 'COR-005', stock: 5, stockMinimo: 2, precioCompra: 28.00, precioVenta: 65.00, proveedor: 'MotorParts EU' },
    { id: 'p6', nombre: 'Líquido de frenos DOT4', descripcion: 'Líquido de frenos DOT4, 500ml', sku: 'LIQ-006', stock: 15, stockMinimo: 6, precioCompra: 4.50, precioVenta: 9.90, proveedor: 'FrenoBrake Pro' },
    { id: 'p7', nombre: 'Amortiguador trasero', descripcion: 'Amortiguador gas trasero universal', sku: 'AMO-007', stock: 4, stockMinimo: 2, precioCompra: 45.00, precioVenta: 95.00, proveedor: 'SuspenPro' },
    { id: 'p8', nombre: 'Filtro de aire', descripcion: 'Filtro de aire panel para cajas de filtración', sku: 'FLT-008', stock: 18, stockMinimo: 5, precioCompra: 6.00, precioVenta: 14.50, proveedor: 'AutoParts SL' },
    { id: 'p9', nombre: 'Batería 60Ah', descripcion: 'Batería de arranque 60Ah 12V libre mantenimiento', sku: 'BAT-009', stock: 3, stockMinimo: 2, precioCompra: 75.00, precioVenta: 130.00, proveedor: 'ElectroCar' },
    { id: 'p10', nombre: 'Bomba de agua', descripcion: 'Bomba de agua para sistema de refrigeración', sku: 'BOM-010', stock: 6, stockMinimo: 2, precioCompra: 32.00, precioVenta: 70.00, proveedor: 'MotorParts EU' },
    { id: 'p11', nombre: 'Kit embrague', descripcion: 'Kit completo embrague (disco, plato, rodamiento)', sku: 'EMB-011', stock: 2, stockMinimo: 1, precioCompra: 110.00, precioVenta: 220.00, proveedor: 'TransParts' },
    { id: 'p12', nombre: 'Termostato motor', descripcion: 'Termostato refrigeración 87°C universal', sku: 'TER-012', stock: 7, stockMinimo: 3, precioCompra: 8.00, precioVenta: 19.90, proveedor: 'MotorParts EU' },
    { id: 'p13', nombre: 'Sensor O2 / Lambda', descripcion: 'Sonda lambda universal para escape 4 cables', sku: 'SEN-013', stock: 4, stockMinimo: 2, precioCompra: 22.00, precioVenta: 49.00, proveedor: 'ElectroCar' },
    { id: 'p14', nombre: 'Escobillas limpiaparabrisas 60cm', descripcion: 'Escobillas planas universales 600mm', sku: 'ESC-014', stock: 20, stockMinimo: 8, precioCompra: 5.00, precioVenta: 12.00, proveedor: 'AutoParts SL' },
    { id: 'p15', nombre: 'Líquido refrigerante (-35°)', descripcion: 'Anticongelante orgánico OAT 1.5L', sku: 'REF-015', stock: 12, stockMinimo: 5, precioCompra: 7.50, precioVenta: 16.00, proveedor: 'LubriMax SA' },
  ],
  costos: [
    { id: 'c1', fecha: '2025-12-05', categoria: 'piezas', descripcion: 'Compra stock filtros y aceites', importe: 320.00, proveedor: 'AutoParts SL' },
    { id: 'c2', fecha: '2025-12-10', categoria: 'externo', descripcion: 'Servicio limpieza inyectores (externalizado)', importe: 85.00, proveedor: 'CleanMotor' },
    { id: 'c3', fecha: '2025-12-15', categoria: 'general', descripcion: 'Alquiler local diciembre', importe: 650.00, proveedor: '' },
    { id: 'c4', fecha: '2025-12-20', categoria: 'general', descripcion: 'Electricidad y agua diciembre', importe: 120.00, proveedor: '' },
    { id: 'c5', fecha: '2026-01-03', categoria: 'piezas', descripcion: 'Reposición pastillas y discos', importe: 280.00, proveedor: 'FrenoBrake Pro' },
    { id: 'c6', fecha: '2026-01-15', categoria: 'general', descripcion: 'Alquiler local enero', importe: 650.00, proveedor: '' },
    { id: 'c7', fecha: '2026-02-02', categoria: 'piezas', descripcion: 'Compra baterías y sensores', importe: 450.00, proveedor: 'ElectroCar' },
    { id: 'c8', fecha: '2026-02-18', categoria: 'externo', descripcion: 'Gestoría y asesoría fiscal', importe: 200.00, proveedor: 'Asesoría Díaz' },
    { id: 'c9', fecha: '2026-03-01', categoria: 'general', descripcion: 'Alquiler local marzo', importe: 650.00, proveedor: '' },
    { id: 'c10', fecha: '2026-03-12', categoria: 'piezas', descripcion: 'Compra amortiguadores y kits embrague', importe: 680.00, proveedor: 'SuspenPro' },
  ],
  ventas: [
    { id: 'v1', fecha: '2025-12-08', tipo: 'producto', descripcion: 'Cambio aceite + filtro', importe: 68.00, costo: 28.00 },
    { id: 'v2', fecha: '2025-12-12', tipo: 'servicio', descripcion: 'Revisión frenos completa', importe: 120.00, costo: 42.00 },
    { id: 'v3', fecha: '2025-12-18', tipo: 'producto', descripcion: 'Venta bujías + cambio', importe: 55.00, costo: 20.00 },
    { id: 'v4', fecha: '2025-12-22', tipo: 'servicio', descripcion: 'Alineación y equilibrado', importe: 65.00, costo: 15.00 },
    { id: 'v5', fecha: '2026-01-05', tipo: 'producto', descripcion: 'Cambio pastillas delanteras', importe: 95.00, costo: 38.00 },
    { id: 'v6', fecha: '2026-01-14', tipo: 'servicio', descripcion: 'Diagnóstico electrónico + reparación', importe: 180.00, costo: 55.00 },
    { id: 'v7', fecha: '2026-02-03', tipo: 'producto', descripcion: 'Instalación batería 60Ah', importe: 155.00, costo: 80.00 },
    { id: 'v8', fecha: '2026-02-20', tipo: 'servicio', descripcion: 'Cambio correa distribución', importe: 220.00, costo: 90.00 },
    { id: 'v9', fecha: '2026-03-07', tipo: 'producto', descripcion: 'Cambio amortiguadores traseros (2 uds)', importe: 310.00, costo: 140.00 },
    { id: 'v10', fecha: '2026-03-15', tipo: 'servicio', descripcion: 'ITV pre-inspección + ajustes', importe: 85.00, costo: 25.00 },
    { id: 'v11', fecha: '2026-04-02', tipo: 'producto', descripcion: 'Cambio aceite + filtros', importe: 72.00, costo: 30.00 },
    { id: 'v12', fecha: '2026-04-10', tipo: 'servicio', descripcion: 'Reparación sistema refrigeración', importe: 195.00, costo: 75.00 },
  ]
};
